export const songs = [
	{
		index: 1,
		title: "Lose Yourself",
		artist: "Peaches & Herb",
		album: "Sing Me A Lullaby, My Sweet Temptation",
		genre: "Halloween",
		likes: 23,
		audio: "/api/songs/audio/1/1",
		audioFile: "audio\\song-1-1.mid",
	},
	{
		index: 2,
		title: "All I Have to Do is Dream",
		artist: "Bizarrap",
		album: "Taylor Swift",
		genre: "Acid Rock",
		likes: 12,
		audio: "/api/songs/audio/1/2",
		audioFile: "audio\\song-1-2.mid",
	},
	{
		index: 3,
		title: "Mack the Knife",
		artist: "The O'Jays",
		album: "What Is Love?",
		genre: "Drinking Songs",
		likes: 17,
		audio: "/api/songs/audio/1/3",
		audioFile: "audio\\song-1-3.mid",
	},
	{
		index: 4,
		title: "It's All in the Game",
		artist: "Becky G",
		album: "Berlin Lebt",
		genre: "Flamenco",
		likes: 14,
		audio: "/api/songs/audio/1/4",
		audioFile: "audio\\song-1-4.mid",
	},
	{
		index: 5,
		title: "Rock Your Baby",
		artist: "Vance Joy",
		album: "The Papercut Chronicles",
		genre: "Acoustic Blues",
		likes: 13,
		audio: "/api/songs/audio/1/5",
		audioFile: "audio\\song-1-5.mid",
	},
	{
		index: 6,
		title: "Somebody That I Used to Know",
		artist: "Daft Punk",
		album: "Away From The Sun",
		genre: "Drill",
		likes: 22,
		audio: "/api/songs/audio/1/6",
		audioFile: "audio\\song-1-6.mid",
	},
	{
		index: 7,
		title: "Nature Boy",
		artist: "Tammi Terrell",
		album: "God's Project",
		genre: "Baladas y Boleros",
		likes: 19,
		audio: "/api/songs/audio/1/7",
		audioFile: "audio\\song-1-7.mid",
	},
	{
		index: 8,
		title: "Give Me Everything",
		artist: "Rosemary Clooney",
		album: "Stronger",
		genre: "Halloween",
		likes: 7,
		audio: "/api/songs/audio/1/8",
		audioFile: "audio\\song-1-8.mid",
	},
	{
		index: 9,
		title: "Got to Give it Up",
		artist: "Fanny Brice",
		album: "No Me Pidas Perdón",
		genre: "Reggae",
		likes: 12,
		audio: "/api/songs/audio/1/9",
		audioFile: "audio\\song-1-9.mid",
	},
	{
		index: 10,
		title: "Don't You (Forget About Me)",
		artist: "Kelly Clarkson",
		album: "Dark Horse",
		genre: "Musicals",
		likes: 10,
		audio: "/api/songs/audio/1/10",
		audioFile: "audio\\song-1-10.mid",
	},
	{
		index: 11,
		title: "Dancing in the Dark",
		artist: "Diddy",
		album: "Charlie's Angels",
		genre: "Acid Rock",
		likes: 8,
		audio: "/api/songs/audio/1/11",
		audioFile: "audio\\song-1-11.mid",
	},
	{
		index: 12,
		title: "Poker Face",
		artist: "Chicago",
		album: "Reclassified",
		genre: "Tango",
		likes: 8,
		audio: "/api/songs/audio/1/12",
		audioFile: "audio\\song-1-12.mid",
	},
	{
		index: 13,
		title: "Physical",
		artist: "Gladys Knight & The Pips",
		album: "Minutes To Midnight",
		genre: "Southern Gospel",
		likes: 16,
		audio: "/api/songs/audio/1/13",
		audioFile: "audio\\song-1-13.mid",
	},
	{
		index: 14,
		title: "Too Young",
		artist: "Bethel Music",
		album: "A Day Without Rain",
		genre: "American Trad Rock",
		likes: 20,
		audio: "/api/songs/audio/1/14",
		audioFile: "audio\\song-1-14.mid",
	},
	{
		index: 15,
		title: "Hey There Delilah",
		artist: "Roxette",
		album: "CNCO",
		genre: "Hard Rock",
		likes: 9,
		audio: "/api/songs/audio/1/15",
		audioFile: "audio\\song-1-15.mid",
	},
	{
		index: 16,
		title: "Something",
		artist: "Juan Gabriel",
		album: "Crash Talk",
		genre: "Electro",
		likes: 8,
		audio: "/api/songs/audio/1/16",
		audioFile: "audio\\song-1-16.mid",
	},
	{
		index: 17,
		title: "Rhapsody in Blue",
		artist: "Asees Kaur",
		album: "Sweet Talker",
		genre: "Avant-Punk",
		likes: 9,
		audio: "/api/songs/audio/1/17",
		audioFile: "audio\\song-1-17.mid",
	},
	{
		index: 18,
		title: "Gimme Some Lovin'",
		artist: "DAY6",
		album: "Full Moon Fever",
		genre: "Downtempo",
		likes: 11,
		audio: "/api/songs/audio/1/18",
		audioFile: "audio\\song-1-18.mid",
	},
	{
		index: 19,
		title: "Are You Lonesome Tonight?",
		artist: "Miranda Lambert",
		album: "Baby On Baby",
		genre: "Celtic Folk",
		likes: 18,
		audio: "/api/songs/audio/1/19",
		audioFile: "audio\\song-1-19.mid",
	},
	{
		index: 20,
		title: "A Hard Day's Night",
		artist: "C. Tangana",
		album: "Nimrod",
		genre: "OPM",
		likes: 8,
		audio: "/api/songs/audio/1/20",
		audioFile: "audio\\song-1-20.mid",
	},
	{
		index: 21,
		title: "Three Times a Lady",
		artist: "Ruth B.",
		album: "El Malo",
		genre: "Kids",
		likes: 22,
		audio: "/api/songs/audio/1/21",
		audioFile: "audio\\song-1-21.mid",
	},
	{
		index: 22,
		title: "Chances Are",
		artist: "Los Tigres Del Norte",
		album: "Buds",
		genre: "Afro-Pop",
		likes: 22,
		audio: "/api/songs/audio/1/22",
		audioFile: "audio\\song-1-22.mid",
	},
	{
		index: 23,
		title: "(Sittin' On) the Dock of the Bay",
		artist: "The Village People",
		album: "Battleground",
		genre: "Minimal Techno",
		likes: 21,
		audio: "/api/songs/audio/1/23",
		audioFile: "audio\\song-1-23.mid",
	},
	{
		index: 24,
		title: "Careless Whisper",
		artist: "Rod Wave",
		album: "Break The Cycle",
		genre: "Zydeco",
		likes: 5,
		audio: "/api/songs/audio/1/24",
		audioFile: "audio\\song-1-24.mid",
	},
	{
		index: 25,
		title: "Don't Stop 'Til You Get Enough",
		artist: "Plan B",
		album: "Kinks (You Really Got Me)",
		genre: "Alt-Rock",
		likes: 11,
		audio: "/api/songs/audio/1/25",
		audioFile: "audio\\song-1-25.mid",
	},
	{
		index: 26,
		title: "You're the One That I Want",
		artist: "Lisa Loeb",
		album: "The Head And The Heart",
		genre: "Space Rock",
		likes: 22,
		audio: "/api/songs/audio/1/26",
		audioFile: "audio\\song-1-26.mid",
	},
	{
		index: 27,
		title: "The Christmas Song (Chestnuts Roasting On An Open Fire)",
		artist: "Mark Ronson",
		album: "Breakfast In America",
		genre: "Hair Metal",
		likes: 5,
		audio: "/api/songs/audio/1/27",
		audioFile: "audio\\song-1-27.mid",
	},
	{
		index: 28,
		title: "Brandy (You're A Fine Girl)",
		artist: "The Beatles",
		album: "Sweet Talker",
		genre: "Space Rock",
		likes: 7,
		audio: "/api/songs/audio/1/28",
		audioFile: "audio\\song-1-28.mid",
	},
	{
		index: 29,
		title: "(Ghost) Riders in the Sky",
		artist: "Anderson .Paak",
		album: "Langit Mong Bughaw",
		genre: "No Wave",
		likes: 12,
		audio: "/api/songs/audio/1/29",
		audioFile: "audio\\song-1-29.mid",
	},
	{
		index: 30,
		title: "Frankenstein",
		artist: "Bee Gees",
		album: "Grand Champ",
		genre: "Southern Gospel",
		likes: 16,
		audio: "/api/songs/audio/1/30",
		audioFile: "audio\\song-1-30.mid",
	},
	{
		index: 31,
		title: "Silly Love Songs",
		artist: "The Black Keys",
		album: "Ferxxocalipsis",
		genre: "CCM",
		likes: 9,
		audio: "/api/songs/audio/1/31",
		audioFile: "audio\\song-1-31.mid",
	},
	{
		index: 32,
		title: "Whoomp! (There it Is)",
		artist: "The Score",
		album: "Hey World",
		genre: "Dance",
		likes: 6,
		audio: "/api/songs/audio/1/32",
		audioFile: "audio\\song-1-32.mid",
	},
	{
		index: 33,
		title: "Love's Theme",
		artist: "2 Chainz",
		album: "Toulouse Street",
		genre: "West Coast Rap",
		likes: 23,
		audio: "/api/songs/audio/1/33",
		audioFile: "audio\\song-1-33.mid",
	},
	{
		index: 34,
		title: "Walk On the Wild Side",
		artist: "Myke Towers",
		album: "Urban Hymns",
		genre: "Progressive Rock",
		likes: 24,
		audio: "/api/songs/audio/1/34",
		audioFile: "audio\\song-1-34.mid",
	},
	{
		index: 35,
		title: "(Sittin' On) the Dock of the Bay",
		artist: "Sasha Alex Sloan",
		album: "Generationwhy",
		genre: "Noise",
		likes: 23,
		audio: "/api/songs/audio/1/35",
		audioFile: "audio\\song-1-35.mid",
	},
	{
		index: 36,
		title: "When a Man Loves a Woman",
		artist: "$NOT",
		album: "That's Christmas To Me",
		genre: "Gospel",
		likes: 13,
		audio: "/api/songs/audio/1/36",
		audioFile: "audio\\song-1-36.mid",
	},
	{
		index: 37,
		title: "19th Nervous Breakdown",
		artist: "Oliver Heldens",
		album: "What You See Is What You Get / What You See Ain't Always What You Get",
		genre: "Rock",
		likes: 18,
		audio: "/api/songs/audio/1/37",
		audioFile: "audio\\song-1-37.mid",
	},
	{
		index: 38,
		title: "Honky Tonk Woman",
		artist: "Anton Karas",
		album: "Recuerden Mi Estilo",
		genre: "Lullabies",
		likes: 8,
		audio: "/api/songs/audio/1/38",
		audioFile: "audio\\song-1-38.mid",
	},
	{
		index: 39,
		title: "Rehab",
		artist: "Key Glock",
		album: "God's Project",
		genre: "Roots Rock",
		likes: 24,
		audio: "/api/songs/audio/1/39",
		audioFile: "audio\\song-1-39.mid",
	},
	{
		index: 40,
		title: "Viva La Vida",
		artist: "Angus & Julia Stone",
		album: "Tragic Kingdom",
		genre: "Chicago House",
		likes: 20,
		audio: "/api/songs/audio/1/40",
		audioFile: "audio\\song-1-40.mid",
	},
	{
		index: 41,
		title: "Third Man Theme",
		artist: "Culture Club",
		album: "The Predator",
		genre: "Metalcore",
		likes: 22,
		audio: "/api/songs/audio/1/41",
		audioFile: "audio\\song-1-41.mid",
	},
	{
		index: 42,
		title: "Da Doo Ron Ron (When He Walked Me Home)",
		artist: "Roberta Flack",
		album: "Just As I Am",
		genre: "Musique Concrète",
		likes: 16,
		audio: "/api/songs/audio/1/42",
		audioFile: "audio\\song-1-42.mid",
	},
	{
		index: 43,
		title: "King of the Road",
		artist: "Harris Jayaraj",
		album: "Limon Y Sal",
		genre: "Old School Rap",
		likes: 10,
		audio: "/api/songs/audio/1/43",
		audioFile: "audio\\song-1-43.mid",
	},
	{
		index: 44,
		title: "Cherry Pink & Apple Blossom White",
		artist: "Nancy Sinatra",
		album: "Crash Talk",
		genre: "Big Band",
		likes: 17,
		audio: "/api/songs/audio/1/44",
		audioFile: "audio\\song-1-44.mid",
	},
	{
		index: 45,
		title: "Pon De Replay",
		artist: "Al Jolson",
		album: "Is This It",
		genre: "Hardcore Punk",
		likes: 8,
		audio: "/api/songs/audio/1/45",
		audioFile: "audio\\song-1-45.mid",
	},
	{
		index: 46,
		title: "Mule Train",
		artist: "Billy Preston",
		album: "Non-Fiction",
		genre: "Jam Bands",
		likes: 22,
		audio: "/api/songs/audio/1/46",
		audioFile: "audio\\song-1-46.mid",
	},
	{
		index: 47,
		title: "Vision of Love",
		artist: "Agust D",
		album: "The Hardest Love",
		genre: "Mainstream Jazz",
		likes: 17,
		audio: "/api/songs/audio/1/47",
		audioFile: "audio\\song-1-47.mid",
	},
	{
		index: 48,
		title: "Honky Tonk",
		artist: "Mon Laferte",
		album: "Nimrod",
		genre: "Experimental",
		likes: 14,
		audio: "/api/songs/audio/1/48",
		audioFile: "audio\\song-1-48.mid",
	},
	{
		index: 49,
		title: "Last Train to Clarksville",
		artist: "TWICE",
		album: "Saturation III",
		genre: "Romance",
		likes: 22,
		audio: "/api/songs/audio/1/49",
		audioFile: "audio\\song-1-49.mid",
	},
	{
		index: 50,
		title: "Breathe",
		artist: "Colby O'Donis",
		album: "Smithereens",
		genre: "Americana",
		likes: 24,
		audio: "/api/songs/audio/1/50",
		audioFile: "audio\\song-1-50.mid",
	},
	{
		index: 51,
		title: "Over There",
		artist: "Miranda Lambert",
		album: "A Gift & A Curse",
		genre: "Stage And Screen",
		likes: 17,
		audio: "/api/songs/audio/1/51",
		audioFile: "audio\\song-1-51.mid",
	},
	{
		index: 52,
		title: "On My Own",
		artist: "Nayer",
		album: "Staying At Tamara's",
		genre: "Deep House",
		likes: 5,
		audio: "/api/songs/audio/1/52",
		audioFile: "audio\\song-1-52.mid",
	},
	{
		index: 53,
		title: "Grease",
		artist: "Thelma Houston",
		album: "Human",
		genre: "Mariachi",
		likes: 6,
		audio: "/api/songs/audio/1/53",
		audioFile: "audio\\song-1-53.mid",
	},
	{
		index: 54,
		title: "Venus",
		artist: "The Go Gos",
		album: "No Strings Attached",
		genre: "Reggae",
		likes: 16,
		audio: "/api/songs/audio/1/54",
		audioFile: "audio\\song-1-54.mid",
	},
	{
		index: 55,
		title: "Love's Theme",
		artist: "Count Basie",
		album: "High School Musical",
		genre: "Easter",
		likes: 18,
		audio: "/api/songs/audio/1/55",
		audioFile: "audio\\song-1-55.mid",
	},
	{
		index: 56,
		title: "Na Na Hey Hey (Kiss Him Goodbye)",
		artist: "XXXTENTACION",
		album: "A Day Without Rain",
		genre: "Relaxation",
		likes: 8,
		audio: "/api/songs/audio/1/56",
		audioFile: "audio\\song-1-56.mid",
	},
	{
		index: 57,
		title: "Believe",
		artist: "SCH",
		album: "Away From The Sun",
		genre: "Chant",
		likes: 23,
		audio: "/api/songs/audio/1/57",
		audioFile: "audio\\song-1-57.mid",
	},
	{
		index: 58,
		title: "Like a Rolling Stone",
		artist: "The Cowsills",
		album: "Rise Of An Empire",
		genre: "Ambient",
		likes: 7,
		audio: "/api/songs/audio/1/58",
		audioFile: "audio\\song-1-58.mid",
	},
	{
		index: 59,
		title: "Sugar Shack",
		artist: "Johnny Nash",
		album: "Vices & Virtues",
		genre: "Soft Rock",
		likes: 15,
		audio: "/api/songs/audio/1/59",
		audioFile: "audio\\song-1-59.mid",
	},
	{
		index: 60,
		title: "After You've Gone",
		artist: "MC Hammer",
		album: "K.O.",
		genre: "Meditation",
		likes: 8,
		audio: "/api/songs/audio/1/60",
		audioFile: "audio\\song-1-60.mid",
	},
	{
		index: 61,
		title: "Hello Dolly",
		artist: "deadmau5",
		album: "Got Your Six",
		genre: "Traditional",
		likes: 10,
		audio: "/api/songs/audio/1/61",
		audioFile: "audio\\song-1-61.mid",
	},
	{
		index: 62,
		title: "Say You, Say Me",
		artist: "Ciara",
		album: "Drive",
		genre: "Progressive Rock",
		likes: 7,
		audio: "/api/songs/audio/1/62",
		audioFile: "audio\\song-1-62.mid",
	},
	{
		index: 63,
		title: "The Letter",
		artist: "Sophie Ellis-Bextor",
		album: "Nimrod",
		genre: "Blues",
		likes: 16,
		audio: "/api/songs/audio/1/63",
		audioFile: "audio\\song-1-63.mid",
	},
	{
		index: 64,
		title: "Blurred Lines",
		artist: "David Bowie",
		album: "DeAnn",
		genre: "Grime",
		likes: 15,
		audio: "/api/songs/audio/1/64",
		audioFile: "audio\\song-1-64.mid",
	},
	{
		index: 65,
		title: "One Sweet Day",
		artist: "Anitta",
		album: "Pa' Luego Es Tarde",
		genre: "Baladas y Boleros",
		likes: 10,
		audio: "/api/songs/audio/1/65",
		audioFile: "audio\\song-1-65.mid",
	},
	{
		index: 66,
		title: "I Got You (I Feel Good)",
		artist: "Percy Faith",
		album: "Nine Track Mind",
		genre: "Death Metal",
		likes: 13,
		audio: "/api/songs/audio/1/66",
		audioFile: "audio\\song-1-66.mid",
	},
	{
		index: 67,
		title: "I'll be seeing you",
		artist: "The Bangles",
		album: "Modo Avión",
		genre: "Rocksteady",
		likes: 10,
		audio: "/api/songs/audio/1/67",
		audioFile: "audio\\song-1-67.mid",
	},
	{
		index: 68,
		title: "Moonlight Cocktail",
		artist: "Janet Jackson",
		album: "Time",
		genre: "Cajun",
		likes: 12,
		audio: "/api/songs/audio/1/68",
		audioFile: "audio\\song-1-68.mid",
	},
	{
		index: 69,
		title: "Do Ya Think I'm Sexy?",
		artist: "Frankie Avalon",
		album: "Carnival",
		genre: "Mawwal",
		likes: 20,
		audio: "/api/songs/audio/1/69",
		audioFile: "audio\\song-1-69.mid",
	},
	{
		index: 70,
		title: "Sexyback",
		artist: "Sam Cooke",
		album: "Dig Your Roots",
		genre: "Pop",
		likes: 13,
		audio: "/api/songs/audio/1/70",
		audioFile: "audio\\song-1-70.mid",
	},
	{
		index: 71,
		title: "Fantasy",
		artist: "Carly Simon",
		album: "Carnival",
		genre: "Western Swing",
		likes: 5,
		audio: "/api/songs/audio/1/71",
		audioFile: "audio\\song-1-71.mid",
	},
	{
		index: 72,
		title: "Rum & Coca-Cola",
		artist: "Sabrina Carpenter",
		album: "Where The Light Is",
		genre: "Musique Concrète",
		likes: 16,
		audio: "/api/songs/audio/1/72",
		audioFile: "audio\\song-1-72.mid",
	},
	{
		index: 73,
		title: "I Can't Get Next to You",
		artist: "Robin Thicke",
		album: "Hot Sauce / Hello Future",
		genre: "Grime",
		likes: 5,
		audio: "/api/songs/audio/1/73",
		audioFile: "audio\\song-1-73.mid",
	},
	{
		index: 74,
		title: "Little Darlin'",
		artist: "David Guetta",
		album: "News Of The World",
		genre: "Bossa Nova",
		likes: 24,
		audio: "/api/songs/audio/1/74",
		audioFile: "audio\\song-1-74.mid",
	},
	{
		index: 75,
		title: "Nights in White Satin",
		artist: "Bruno & Marrone",
		album: "Younger Now",
		genre: "J-Idol",
		likes: 16,
		audio: "/api/songs/audio/1/75",
		audioFile: "audio\\song-1-75.mid",
	},
	{
		index: 76,
		title: "I Can Help",
		artist: "Melanie Martinez",
		album: "Bobby Tarantino",
		genre: "Electronica",
		likes: 6,
		audio: "/api/songs/audio/1/76",
		audioFile: "audio\\song-1-76.mid",
	},
	{
		index: 77,
		title: "U Can't Touch This",
		artist: "Ice Cube",
		album: "Il Ballo Della Vita",
		genre: "Impressionist",
		likes: 14,
		audio: "/api/songs/audio/1/77",
		audioFile: "audio\\song-1-77.mid",
	},
	{
		index: 78,
		title: "The Loco-Motion",
		artist: "Bebe Rexha",
		album: "Common Sense",
		genre: "Cool Jazz",
		likes: 14,
		audio: "/api/songs/audio/1/78",
		audioFile: "audio\\song-1-78.mid",
	},
	{
		index: 79,
		title: "Cherry Pink & Apple Blossom White",
		artist: "Luis Miguel",
		album: "Luv Is Rage",
		genre: "Rap",
		likes: 10,
		audio: "/api/songs/audio/1/79",
		audioFile: "audio\\song-1-79.mid",
	},
	{
		index: 80,
		title: "Hey There",
		artist: "Guess Who",
		album: "Daydream",
		genre: "West Coast Rap",
		likes: 12,
		audio: "/api/songs/audio/1/80",
		audioFile: "audio\\song-1-80.mid",
	},
	{
		index: 81,
		title: "Kiss You All Over",
		artist: "Tommy Dorsey",
		album: "Clandestino",
		genre: "Space Rock",
		likes: 9,
		audio: "/api/songs/audio/1/81",
		audioFile: "audio\\song-1-81.mid",
	},
	{
		index: 82,
		title: "Purple Haze",
		artist: "Soda Stereo",
		album: "At. Long. Last. ASAP",
		genre: "Emo",
		likes: 8,
		audio: "/api/songs/audio/1/82",
		audioFile: "audio\\song-1-82.mid",
	},
	{
		index: 83,
		title: "Let's Hear it For the Boy",
		artist: "Dean Martin",
		album: "Good Evening",
		genre: "Chanukah",
		likes: 22,
		audio: "/api/songs/audio/1/83",
		audioFile: "audio\\song-1-83.mid",
	},
	{
		index: 84,
		title: "Knock On Wood",
		artist: "Al Green",
		album: "Jamie",
		genre: "Halloween",
		likes: 19,
		audio: "/api/songs/audio/1/84",
		audioFile: "audio\\song-1-84.mid",
	},
	{
		index: 85,
		title: "Cry Like a Baby",
		artist: "Herb Alpert",
		album: "Prisma",
		genre: "Doo-wop",
		likes: 7,
		audio: "/api/songs/audio/1/85",
		audioFile: "audio\\song-1-85.mid",
	},
	{
		index: 86,
		title: "These Boots Are Made For Walking",
		artist: "Fats Waller",
		album: "Disumano",
		genre: "German Pop",
		likes: 18,
		audio: "/api/songs/audio/1/86",
		audioFile: "audio\\song-1-86.mid",
	},
	{
		index: 87,
		title: "Magic Carpet Ride",
		artist: "Nina Simone",
		album: "My Worlds",
		genre: "Environmental",
		likes: 9,
		audio: "/api/songs/audio/1/87",
		audioFile: "audio\\song-1-87.mid",
	},
	{
		index: 88,
		title: "The Sounds of Silence",
		artist: "Pentatonix",
		album: "Lost",
		genre: "Space Rock",
		likes: 5,
		audio: "/api/songs/audio/1/88",
		audioFile: "audio\\song-1-88.mid",
	},
	{
		index: 89,
		title: "Roses Are Red",
		artist: "Mary Wells",
		album: "Her Loss",
		genre: "Punk Rock",
		likes: 17,
		audio: "/api/songs/audio/1/89",
		audioFile: "audio\\song-1-89.mid",
	},
	{
		index: 90,
		title: "Another Brick in the Wall (part 2)",
		artist: "Kacey Musgraves",
		album: "Camino Palmero",
		genre: "Flamenco",
		likes: 7,
		audio: "/api/songs/audio/1/90",
		audioFile: "audio\\song-1-90.mid",
	},
	{
		index: 91,
		title: "You're Beautiful",
		artist: "Billy Preston",
		album: "Lazarus",
		genre: "Retro",
		likes: 17,
		audio: "/api/songs/audio/1/91",
		audioFile: "audio\\song-1-91.mid",
	},
	{
		index: 92,
		title: "Wild Thing",
		artist: "Harry Chapin",
		album: "Depression Cherry",
		genre: "Avant-Garde",
		likes: 15,
		audio: "/api/songs/audio/1/92",
		audioFile: "audio\\song-1-92.mid",
	},
	{
		index: 93,
		title: "Crimson & Clover",
		artist: "Vanessa Williams",
		album: "The Time Of Our Lives",
		genre: "Rap",
		likes: 24,
		audio: "/api/songs/audio/1/93",
		audioFile: "audio\\song-1-93.mid",
	},
	{
		index: 94,
		title: "Pony Time",
		artist: "Sting",
		album: "The Beginning",
		genre: "Smooth Jazz",
		likes: 19,
		audio: "/api/songs/audio/1/94",
		audioFile: "audio\\song-1-94.mid",
	},
	{
		index: 95,
		title: "Lights",
		artist: "Mabel",
		album: "30 De Febrero",
		genre: "Goth",
		likes: 18,
		audio: "/api/songs/audio/1/95",
		audioFile: "audio\\song-1-95.mid",
	},
	{
		index: 96,
		title: "Glory of Love",
		artist: "Sam Cooke",
		album: "Chocolate Factory",
		genre: "Pop Film",
		likes: 7,
		audio: "/api/songs/audio/1/96",
		audioFile: "audio\\song-1-96.mid",
	},
	{
		index: 97,
		title: "Big Bad John",
		artist: "The Temptations",
		album: "Coco",
		genre: "Glam Rock",
		likes: 7,
		audio: "/api/songs/audio/1/97",
		audioFile: "audio\\song-1-97.mid",
	},
	{
		index: 98,
		title: "Puttin' on the Ritz",
		artist: "Saweetie",
		album: "Who Really Cares",
		genre: "Gangsta Rap",
		likes: 6,
		audio: "/api/songs/audio/1/98",
		audioFile: "audio\\song-1-98.mid",
	},
	{
		index: 99,
		title: "Oh, Pretty Woman",
		artist: "The Lemon Pipers",
		album: "Alta Suciedad",
		genre: "Afro-Pop",
		likes: 17,
		audio: "/api/songs/audio/1/99",
		audioFile: "audio\\song-1-99.mid",
	},
	{
		index: 100,
		title: "Shout",
		artist: "Miranda Lambert",
		album: "California Sunrise",
		genre: "Industrial",
		likes: 19,
		audio: "/api/songs/audio/1/100",
		audioFile: "audio\\song-1-100.mid",
	},
];
